version: '3.9'

services:
  blog-mongodb-dev:
    image: mongo:5.0.7
    container_name: blog-mongodb-dev
    restart: always
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo --quiet | grep 1
      interval: 30s
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
    ports:
      - 27017:27017
    networks:
      - main-network
    volumes:
      - mongodb_data:/data/db

  blog-web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: blog-web-dev
    environment:
      - REACT_APP_PUBLIC_API=http://localhost:3001
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
      - ./cypress:/usr/src/app/cypress
    depends_on:
      blog-api-dev:
        condition: service_healthy
    ports:
      - 3000:3000
    networks:
      - main-network

  blog-api-dev:
    image: pedro0505/blog-api:1.0.0
    container_name: blog-api-dev
    depends_on:
      blog-mongodb-dev:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 3001:3001
    environment:
      - DATABASE_URL=mongodb://blog-mongodb-dev:27017/blog
      - PORT_API=3001
    networks:
      - main-network

volumes:
  mongodb_data:
    driver: local

networks:
  main-network:
    driver: bridge
