version: '3.9'

services:
  blog-mongodb-test:
    image: mongo:5.0.7
    container_name: blog-mongodb-test
    restart: always
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo --quiet | grep 1
      interval: 30s
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
    ports:
      - 27017:27017
    networks:
      - main-network

  blog-web-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: blog-web-test
    depends_on:
      blog-api-test:
        condition: service_healthy
    ports:
      - 3000:80
    networks:
      - main-network

  blog-api-test:
    image: pedro0505/blog-api
    container_name: blog-api-test
    depends_on:
      blog-mongodb-test:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 3001:3001
    environment:
      - DATABASE_URL=mongodb://blog-mongodb-test:27017/blog
      - PORT_API=3001
    networks:
      - main-network

networks:
  main-network:
    driver: bridge
