name: Rodando os testes do cypress

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  cypress-e2e-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Verifica o repositório do Git
        uses: actions/checkout@v2

      - name: Sobe os containers
        run: docker-compose -f docker-compose.test.yml up --build -d

      - name: Roda os testes e2e
        run: docker-compose -f docker-compose.test.yml exec -T blog-web-test npx cypress run

      - name: Derruba os containers
        if: always()
        run: docker-compose -f docker-compose.test.yml down --rmi all --volumes --remove-orphans
