name: Rodando o eslint para encontrar erros

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  eslint:
    runs-on: ubuntu-20.04
    steps:
      - name: Verifica o repositório do Git
        uses: actions/checkout@v2

      - name: Instala o node
        uses: actions/setup-node@v2
        with:
          node-version: '16.15.0'

      - name: Instalando as dependências
        run: npm install

      - name: Executando o lint
        run: npx eslint . --ext .ts,.tsx
